#include "BuildIdentity.hpp"
#ifndef FC_BUILD_ID
#error FC_BUILD_ID must be generated by the project CMake configuration.
#endif
#ifndef FC_SOURCE_SHA256
#error FC_SOURCE_SHA256 must be generated by the project CMake configuration.
#endif
// Deliberately independent of SKSE/PCH/CRT, so the exact exported identity unit
// can also be compiled and linked in an SDK-free Windows PE regression fixture.
extern "C" __declspec(dllexport) const char FreedomControl_BuildID[] = FC_BUILD_ID;
extern "C" __declspec(dllexport) const char FreedomControl_SourceSHA256[] =
    "FC-SOURCE-SHA256:" FC_SOURCE_SHA256;
