cmake_minimum_required(VERSION 3.25)
# Script-mode packaging only: no project(), compiler, vcpkg, network, or PowerShell.
# Inputs: FC_ROOT, FC_BUILD (optional; otherwise prefer an existing VS2026 DLL).
# FC_TEST_STATUS is supplied by build.ps1 ONLY after CTest returns success.

if(NOT DEFINED FC_ROOT OR "${FC_ROOT}" STREQUAL "")
    get_filename_component(FC_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
string(REPLACE "\\" "/" FC_ROOT "${FC_ROOT}")
if("${FC_ROOT}" MATCHES ";|\n|\r")
    message(FATAL_ERROR "Project path contains a semicolon or newline; use a normal directory path.")
endif()
file(REAL_PATH "${FC_ROOT}" FC_ROOT)
if(NOT IS_DIRECTORY "${FC_ROOT}")
    message(FATAL_ERROR "Project folder does not exist: ${FC_ROOT}")
endif()
if(NOT DEFINED FC_BUILD OR "${FC_BUILD}" STREQUAL "")
    foreach(_name IN ITEMS vs2026 vs2022)
        if(EXISTS "${FC_ROOT}/build/${_name}/Release/FreedomControl.dll")
            set(FC_BUILD "${FC_ROOT}/build/${_name}")
            break()
        endif()
    endforeach()
endif()
if(NOT DEFINED FC_BUILD OR "${FC_BUILD}" STREQUAL "")
    message(FATAL_ERROR "No existing Release DLL. Run BUILD.bat first. Packaging does not compile a DLL.")
endif()
string(REPLACE "\\" "/" FC_BUILD "${FC_BUILD}")
if("${FC_BUILD}" MATCHES ";|\n|\r")
    message(FATAL_ERROR "Build path contains a semicolon or newline.")
endif()
file(REAL_PATH "${FC_BUILD}" FC_BUILD BASE_DIRECTORY "${FC_ROOT}")
set(_dll "${FC_BUILD}/Release/FreedomControl.dll")
set(_ini "${FC_ROOT}/package/SKSE/Plugins/FreedomControl.ini")
set(_runtime "${FC_ROOT}/package/FreedomControlRuntime.esp")
set(_catalog "${FC_ROOT}/package/SKSE/Plugins/FreedomControl.creatures.json")
foreach(_required IN ITEMS "${_dll}" "${_ini}" "${_runtime}" "${_catalog}" "${FC_BUILD}/CMakeCache.txt")
    if(NOT EXISTS "${_required}" OR IS_DIRECTORY "${_required}")
        message(FATAL_ERROR "Required input file is missing: ${_required}")
    endif()
endforeach()

# Read cache entries as DATA; never execute/include a cache file as a script.
function(fc_cache key output)
    file(STRINGS "${FC_BUILD}/CMakeCache.txt" _lines
        REGEX "^${key}:[^=]*=" ENCODING UTF-8)
    set(_value "")
    foreach(_line IN LISTS _lines)
        string(FIND "${_line}" "=" _equal)
        math(EXPR _start "${_equal} + 1")
        string(SUBSTRING "${_line}" ${_start} -1 _value)
        break()
    endforeach()
    set(${output} "${_value}" PARENT_SCOPE)
endfunction()
fc_cache(CMAKE_HOME_DIRECTORY _cache_root)
if("${_cache_root}" STREQUAL "")
    message(FATAL_ERROR "CMakeCache.txt has no source directory; refusing to package an unidentified build.")
endif()
string(REPLACE "\\" "/" _cache_root "${_cache_root}")
file(REAL_PATH "${_cache_root}" _cache_root)
set(_expected_root "${FC_ROOT}")
if(CMAKE_HOST_WIN32)
    string(TOLOWER "${_expected_root}" _expected_root)
    string(TOLOWER "${_cache_root}" _cache_root)
endif()
if(NOT "${_cache_root}" STREQUAL "${_expected_root}")
    message(FATAL_ERROR "This build belongs to a different source directory. Existing outputs are unchanged.")
endif()

# Small bounded PE-header reader. This checks architecture/type, NOT in-game ABI.
function(fc_uint offset width output)
    math(EXPR _end "${offset} + ${width}")
    if(offset LESS 0 OR _end GREATER _dll_size)
        message(FATAL_ERROR "Truncated/invalid PE header in ${_dll}")
    endif()
    file(READ "${_dll}" _hex OFFSET ${offset} LIMIT ${width} HEX)
    string(LENGTH "${_hex}" _length)
    math(EXPR _wanted "${width} * 2")
    if(NOT _length EQUAL _wanted)
        message(FATAL_ERROR "Could not read the complete PE header.")
    endif()
    set(_value 0)
    math(EXPR _last "${width} - 1")
    foreach(_i RANGE 0 ${_last})
        math(EXPR _pos "${_i} * 2")
        string(SUBSTRING "${_hex}" ${_pos} 2 _byte)
        math(EXPR _value "${_value} | (0x${_byte} << (8 * ${_i}))")
    endforeach()
    set(${output} ${_value} PARENT_SCOPE)
endfunction()
file(SIZE "${_dll}" _dll_size)
if(_dll_size LESS 128)
    message(FATAL_ERROR "DLL is too short to be a Windows PE file.")
endif()
fc_uint(0 2 _mz)
fc_uint(60 4 _pe)
if(NOT _mz EQUAL 23117 OR _pe LESS 64)
    message(FATAL_ERROR "Output is not a valid Windows PE file.")
endif()
fc_uint(${_pe} 4 _signature)
math(EXPR _offset "${_pe} + 4")
fc_uint(${_offset} 2 _machine)
math(EXPR _offset "${_pe} + 6")
fc_uint(${_offset} 2 _sections)
math(EXPR _offset "${_pe} + 20")
fc_uint(${_offset} 2 _optional_size)
math(EXPR _offset "${_pe} + 22")
fc_uint(${_offset} 2 _characteristics)
math(EXPR _dll_flag "${_characteristics} & 0x2000")
math(EXPR _optional "${_pe} + 24")
fc_uint(${_optional} 2 _magic)
math(EXPR _headers_end "${_optional} + ${_optional_size} + ${_sections} * 40")
if(NOT _signature EQUAL 17744 OR NOT _machine EQUAL 34404 OR
        NOT _dll_flag OR NOT _magic EQUAL 523 OR _optional_size LESS 112 OR
        _sections LESS 1 OR _headers_end GREATER _dll_size)
    message(FATAL_ERROR "Output is not a complete x64 PE32+ DLL. No ZIP was replaced.")
endif()
# Check exact bytes, not regex/string-decoding heuristics. An ID check is not
# enough: every plugin translation unit also carries the source-hash definition.
include("${CMAKE_CURRENT_LIST_DIR}/SourceIdentity.cmake")
fc_source_identity("${FC_ROOT}" _expected_build_id _expected_source_sha _source_files)
file(READ "${_dll}" _dll_hex HEX)
foreach(_label IN ITEMS RELEASE SOURCE)
    if(_label STREQUAL "RELEASE")
        set(_expected "${_expected_build_id}")
    else()
        set(_expected "FC-SOURCE-SHA256:${_expected_source_sha}")
    endif()
    string(HEX "${_expected}" _needle)
    string(FIND "${_dll_hex}" "${_needle}00" _found)
    if(_found LESS 0)
        file(STRINGS "${_dll}" _observed REGEX "FC-0[.][0-9][^ ;]*" LIMIT_COUNT 4
            ENCODING UTF-8 NO_HEX_CONVERSION)
        if(NOT _observed)
            set(_observed "<no readable build marker>")
        endif()
        message(FATAL_ERROR "FC_IDENTITY_MISMATCH (${_label})\n  DLL: ${_dll}\n  Expected: ${_expected}\n  Observed release text: ${_observed}\n  Run REPAIR_BUILD8.bat to rebuild ONLY FreedomControl. Do not run PACKAGE_ONLY on a stale DLL. No ZIP was replaced.")
    endif()
endforeach()
unset(_dll_hex)
message(STATUS "DLL_IDENTITY_OK: ${_expected_build_id}")
message(STATUS "SOURCE_SHA256_OK: ${_expected_source_sha}")
if(DEFINED FC_CHECK_ONLY AND FC_CHECK_ONLY)
    return()
endif()
file(SHA256 "${_dll}" _dll_hash)
file(SHA256 "${_ini}" _ini_hash)
file(SHA256 "${_runtime}" _runtime_hash)
file(SHA256 "${_catalog}" _catalog_hash)
file(READ "${_runtime}" _runtime_magic LIMIT 4 HEX)
if(NOT "${_runtime_magic}" STREQUAL "54455334")
    message(FATAL_ERROR "Runtime ESP is not a TES4 plugin. No ZIP was replaced.")
endif()
file(READ "${_catalog}" _catalog_json)
string(JSON _catalog_schema ERROR_VARIABLE _json_error GET "${_catalog_json}" schema)
if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _catalog_schema EQUAL 1)
    message(FATAL_ERROR "Creature catalog schema is missing/invalid. No ZIP was replaced.")
endif()
string(JSON _catalog_build ERROR_VARIABLE _json_error GET "${_catalog_json}" build)
if(NOT _json_error STREQUAL "NOTFOUND" OR NOT "${_catalog_build}" STREQUAL "${_expected_build_id}")
    message(FATAL_ERROR "Creature catalog build marker mismatch. No ZIP was replaced.")
endif()
string(JSON _catalog_count ERROR_VARIABLE _json_error LENGTH "${_catalog_json}" entries)
if(NOT _json_error STREQUAL "NOTFOUND" OR _catalog_count LESS 1)
    message(FATAL_ERROR "Creature catalog has no entries. No ZIP was replaced.")
endif()

# Resolve third-party notices before touching an existing release archive.
fc_cache(COMMONLIBSSE_PATH _commonlib)
if("${_commonlib}" STREQUAL "")
    set(_commonlib "${FC_ROOT}/../CommonLibSSE-NG")
endif()
string(REPLACE "\\" "/" _commonlib "${_commonlib}")
set(_commonlib_notices "")
foreach(_name IN ITEMS LICENSE LICENSE.txt LICENSE.md COPYING COPYING.txt COPYING.md
        NOTICE NOTICE.txt NOTICE.md EXCEPTIONS.md)
    if(EXISTS "${_commonlib}/${_name}" AND NOT IS_DIRECTORY "${_commonlib}/${_name}")
        list(APPEND _commonlib_notices "${_commonlib}/${_name}")
    endif()
endforeach()
if(NOT _commonlib_notices AND NOT IS_DIRECTORY "${_commonlib}/licenses")
    message(FATAL_ERROR "CommonLib license/notice file was not found at ${_commonlib}. Keep the original checkout available.")
endif()
foreach(_name IN ITEMS README_zh-CN.md FEATURES_zh-CN.md LICENSE.txt BUILD_STATUS.md)
    if(NOT EXISTS "${FC_ROOT}/${_name}" OR IS_DIRECTORY "${FC_ROOT}/${_name}")
        message(FATAL_ERROR "Source documentation is missing: ${_name}. Extract the complete source ZIP.")
    endif()
endforeach()
if(NOT DEFINED FC_TEST_STATUS OR "${FC_TEST_STATUS}" STREQUAL "")
    set(FC_TEST_STATUS "NOT_RERUN: existing DLL reused; this command only validates and packages files")
endif()

set(_dist "${FC_ROOT}/dist")
file(MAKE_DIRECTORY "${_dist}")
file(LOCK "${_dist}/.freedomcontrol-package.lock" GUARD PROCESS TIMEOUT 0 RESULT_VARIABLE _lock)
if(NOT "${_lock}" STREQUAL "0")
    message(FATAL_ERROR "Another packaging process holds the output lock: ${_lock}")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _nonce)
set(_work "${_dist}/.fc-package-${_nonce}")
set(_stage "${_work}/MO2")
set(_docs "${_stage}/FreedomControl-docs")
set(_zip_name "FreedomControl-0.5.5-VMARGS18-MO2.zip")
set(_temp_zip "${_work}/${_zip_name}")
set(_zip "${_dist}/${_zip_name}")
file(MAKE_DIRECTORY "${_stage}/SKSE/Plugins" "${_docs}/third-party")
file(COPY_FILE "${_dll}" "${_stage}/SKSE/Plugins/FreedomControl.dll")
file(COPY_FILE "${_ini}" "${_stage}/SKSE/Plugins/FreedomControl.ini")
file(COPY_FILE "${_runtime}" "${_stage}/FreedomControlRuntime.esp")
file(COPY_FILE "${_catalog}" "${_stage}/SKSE/Plugins/FreedomControl.creatures.json")
foreach(_name IN ITEMS README_zh-CN.md FEATURES_zh-CN.md LICENSE.txt BUILD_STATUS.md)
    file(COPY_FILE "${FC_ROOT}/${_name}" "${_docs}/${_name}")
endforeach()
if(IS_DIRECTORY "${FC_ROOT}/docs")
    file(COPY "${FC_ROOT}/docs" DESTINATION "${_docs}")
endif()
foreach(_notice IN LISTS _commonlib_notices)
    get_filename_component(_name "${_notice}" NAME)
    file(COPY_FILE "${_notice}" "${_docs}/third-party/CommonLib-${_name}")
endforeach()
# Newer CommonLib checkouts use COPYING.txt + EXCEPTIONS.md + licenses/.
# Keep the complete notice directory rather than assuming a root LICENSE file.
if(IS_DIRECTORY "${_commonlib}/licenses")
    file(COPY "${_commonlib}/licenses/" DESTINATION "${_docs}/third-party/CommonLib-licenses")
endif()
fc_cache(VCPKG_INSTALLED_DIR _vcpkg_dir)
if("${_vcpkg_dir}" STREQUAL "")
    set(_vcpkg_dir "${FC_BUILD}/vcpkg_installed")
endif()
string(REPLACE "\\" "/" _vcpkg_dir "${_vcpkg_dir}")
set(_share "${_vcpkg_dir}/x64-windows-static-md/share")
string(REPLACE "[" "[[]" _share_glob "${_share}")
file(GLOB _copyrights "${_share_glob}/*/copyright")
if(NOT _copyrights)
    message(FATAL_ERROR "vcpkg dependency notices were not found under ${_share}. Keep the dependency cache; no ZIP was replaced.")
endif()
foreach(_notice IN LISTS _copyrights)
    get_filename_component(_dir "${_notice}" DIRECTORY)
    get_filename_component(_name "${_dir}" NAME)
    file(COPY_FILE "${_notice}" "${_docs}/third-party/${_name}-copyright.txt")
endforeach()
fc_cache(CMAKE_GENERATOR _generator)
set(_commit "unknown; no commonlib.lock.txt")
if(EXISTS "${FC_ROOT}/commonlib.lock.txt")
    file(READ "${FC_ROOT}/commonlib.lock.txt" _commit LIMIT 256)
    string(STRIP "${_commit}" _commit)
endif()
string(TIMESTAMP _utc "%Y-%m-%dT%H:%M:%SZ" UTC)
file(TIMESTAMP "${_dll}" _dll_utc "%Y-%m-%dT%H:%M:%SZ" UTC)
file(WRITE "${_docs}/BUILD-INFO.txt"
    "FreedomControl 0.5.5 SexFast16 zh-CN\n"
    "Packaging revision: SexFast16 + Repair15 + full-panel master-audio silence lease + Buildfix8\n"
    "Verified binary build marker: ${_expected_build_id}\n"
    "Verified source SHA256: ${_expected_source_sha}\n"
    "Runtime target: Skyrim 1.6.1170.0\n"
    "DLL input: ${_dll}\n"
    "DLL file timestamp (UTC): ${_dll_utc}\n"
    "CMake cache generator: ${_generator}\n"
    "Packaging CMake: ${CMAKE_VERSION}\n"
    "CommonLib lock entry (metadata, not a binary proof): ${_commit}\n"
    "DLL SHA256: ${_dll_hash}\n"
    "INI SHA256: ${_ini_hash}\n"
    "Runtime ESP SHA256: ${_runtime_hash}\n"
    "Creature catalog SHA256: ${_catalog_hash}\n"
    "Creature catalog entries: ${_catalog_count}\n"
    "Enable FreedomControlRuntime.esp in MO2 right-side Plugins list.\n"
    "Test status: ${FC_TEST_STATUS}\n"
    "Package UTC: ${_utc}\n"
    "Checks: x64 PE32+ DLL header; embedded release and source markers; SHA256; ZIP extraction round-trip.\n"
    "No SKSE loading or Skyrim gameplay is tested by this packaging script.\n")

# A relative archive root is essential for MO2: no enclosing project/Data folder.
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${_temp_zip}" --format=zip --
        SKSE FreedomControlRuntime.esp FreedomControl-docs
    WORKING_DIRECTORY "${_stage}" RESULT_VARIABLE _result
    OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(NOT "${_result}" STREQUAL "0")
    message(FATAL_ERROR "ZIP creation failed (${_result}): ${_out}${_err}. Previous release unchanged.")
endif()
# Actually unpack the new ZIP and compare EVERY staged file before publishing.
set(_verify "${_work}/verify")
file(ARCHIVE_EXTRACT INPUT "${_temp_zip}" DESTINATION "${_verify}")
string(REPLACE "[" "[[]" _stage_glob "${_stage}")
file(GLOB_RECURSE _files RELATIVE "${_stage}" LIST_DIRECTORIES FALSE "${_stage_glob}/*")
list(LENGTH _files _file_count)
if(_file_count LESS 6)
    message(FATAL_ERROR "Archive verification: unexpectedly empty/incomplete staging folder.")
endif()
foreach(_name IN LISTS _files)
    if(NOT EXISTS "${_verify}/${_name}" OR IS_DIRECTORY "${_verify}/${_name}")
        message(FATAL_ERROR "Archive verification: missing ${_name}. Previous release unchanged.")
    endif()
    file(SHA256 "${_stage}/${_name}" _expected)
    file(SHA256 "${_verify}/${_name}" _actual)
    if(NOT "${_expected}" STREQUAL "${_actual}")
        message(FATAL_ERROR "Archive verification: hash mismatch for ${_name}. Previous release unchanged.")
    endif()
endforeach()
file(SHA256 "${_verify}/SKSE/Plugins/FreedomControl.dll" _copied_dll_hash)
file(SHA256 "${_dll}" _current_dll_hash)
if(NOT "${_dll_hash}" STREQUAL "${_copied_dll_hash}" OR
        NOT "${_dll_hash}" STREQUAL "${_current_dll_hash}")
    message(FATAL_ERROR "DLL changed during packaging. Finish the build and retry; previous release unchanged.")
endif()
file(SHA256 "${_temp_zip}" _zip_hash)
file(WRITE "${_work}/checksum.txt" "${_zip_hash}  ${_zip_name}\n")
# Keep the existing ZIP until the complete replacement has passed verification.
file(RENAME "${_temp_zip}" "${_zip}" RESULT _publish)
if(NOT "${_publish}" STREQUAL "0")
    message(FATAL_ERROR "Cannot publish ${_zip}: ${_publish}. Close programs using the old ZIP and retry.")
endif()
# The checksum is ancillary: a locked sidecar must not turn a valid ZIP into BUILD FAILED.
file(RENAME "${_work}/checksum.txt" "${_zip}.sha256" RESULT _sidecar)
if(NOT "${_sidecar}" STREQUAL "0")
    message(WARNING "ZIP is valid, but its .sha256 sidecar could not be replaced: ${_sidecar}")
endif()
file(REMOVE_RECURSE "${_work}")
message(STATUS "PACKAGE COMPLETE: ${_zip}")
message(STATUS "DLL SHA256: ${_dll_hash}")
message(STATUS "ZIP SHA256: ${_zip_hash}")
message(STATUS "No compiler/download/game installation was run by this packaging step.")
