cmake_minimum_required(VERSION 3.25)
# Invoked only by REPAIR_BUILD8.bat / build.ps1 -RebuildPlugin, after configuration.
# Clear the one plugin's Release intermediates/outputs, NEVER dependencies/source.
foreach(_arg IN ITEMS FC_ROOT FC_BUILD)
    if(NOT DEFINED ${_arg} OR "${${_arg}}" STREQUAL "" OR "${${_arg}}" MATCHES ";|\n|\r")
        message(FATAL_ERROR "Invalid/missing ${_arg}; no files removed.")
    endif()
    string(REPLACE "\\" "/" ${_arg} "${${_arg}}")
    file(REAL_PATH "${${_arg}}" ${_arg})
endforeach()
file(REAL_PATH "${FC_ROOT}/build" _build_parent)
get_filename_component(_actual_parent "${FC_BUILD}" DIRECTORY)
set(_root_cmp "${FC_ROOT}")
set(_parent_cmp "${_build_parent}")
set(_actual_cmp "${_actual_parent}")
if(CMAKE_HOST_WIN32)
    string(TOLOWER "${_root_cmp}" _root_cmp)
    string(TOLOWER "${_parent_cmp}" _parent_cmp)
    string(TOLOWER "${_actual_cmp}" _actual_cmp)
endif()
if(NOT _actual_cmp STREQUAL _parent_cmp OR NOT EXISTS "${FC_BUILD}/CMakeCache.txt")
    message(FATAL_ERROR "Refusing plugin-only reset outside this project's build/<generator> folder.")
endif()
file(STRINGS "${FC_BUILD}/CMakeCache.txt" _home REGEX "^CMAKE_HOME_DIRECTORY:INTERNAL=" ENCODING UTF-8)
list(LENGTH _home _count)
if(NOT _count EQUAL 1)
    message(FATAL_ERROR "Cache has no unique source root; nothing removed.")
endif()
string(REGEX REPLACE "^CMAKE_HOME_DIRECTORY:INTERNAL=" "" _home "${_home}")
string(REPLACE "\\" "/" _home "${_home}")
file(REAL_PATH "${_home}" _home)
if(CMAKE_HOST_WIN32)
    string(TOLOWER "${_home}" _home)
endif()
if(NOT _home STREQUAL _root_cmp)
    message(FATAL_ERROR "Cache belongs to another source directory; nothing removed.")
endif()
set(_objects "${FC_BUILD}/FreedomControl.dir/Release")
if(IS_SYMLINK "${FC_BUILD}/FreedomControl.dir" OR IS_SYMLINK "${_objects}" OR
        IS_SYMLINK "${FC_BUILD}/Release")
    message(FATAL_ERROR "Unexpected symlink in plugin outputs; nothing removed.")
endif()
foreach(_extension IN ITEMS dll lib exp pdb ilk)
    if(IS_DIRECTORY "${FC_BUILD}/Release/FreedomControl.${_extension}")
        message(FATAL_ERROR "Expected a file, not directory: FreedomControl.${_extension}. Nothing removed.")
    endif()
endforeach()
if(EXISTS "${_objects}")
    file(REMOVE_RECURSE "${_objects}")
    if(EXISTS "${_objects}")
        message(FATAL_ERROR "Cannot clear plugin intermediate files. Close the game and active builds.")
    endif()
endif()
foreach(_extension IN ITEMS dll lib exp pdb ilk)
    set(_file "${FC_BUILD}/Release/FreedomControl.${_extension}")
    file(REMOVE "${_file}")
    if(EXISTS "${_file}")
        message(FATAL_ERROR "Cannot remove ${_file}. Close processes using this build output.")
    endif()
endforeach()
message(STATUS "PLUGIN-ONLY RESET: FreedomControl Release intermediates and outputs cleared.")
message(STATUS "Preserved: CommonLib, vcpkg, CMakeCache, source, settings, tests, existing MO2 ZIPs.")
